spring:
  application:
    name: sport-web

sport:
  workout:
    name: "${SPORT.WORKOUT.NAME}"
    locale: "${SPORT.WORKOUT.LOCALE}"
    counter: "${SPORT.WORKOUT.COUNTER}"
    source: "${SPORT.WORKOUT.SOURCE}"