spring:
  application:
    name: sport-web

sport:
  workout:
    name: "${SPORT.WORKOUT.NAME:}"
    locale: "${SPORT.WORKOUT.LOCALE:en}"
    counter: "${SPORT.WORKOUT.COUNTER:0}"
    source: "${SPORT.WORKOUT.SOURCE:file}"